site_name: HighTowerGroup - CT
nav:
  - Theme Settings: index.md
  - Header & Footer Scripts: header-footer.md
  - Menu: menu.md
  - Form: form.md
  - WP Blocks: custom-sections.md
theme: readthedocs
extra_css:
  - style.css
